#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="budget")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.budgetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ENGINEER_BUDGET> ENGINEER_BUDGET
		{
			get
			{
				return this.GetTable<ENGINEER_BUDGET>();
			}
		}
		
		public System.Data.Linq.Table<ENGINEER_INFO> ENGINEER_INFO
		{
			get
			{
				return this.GetTable<ENGINEER_INFO>();
			}
		}
		
		public System.Data.Linq.Table<NOT_CLOSE> NOT_CLOSE
		{
			get
			{
				return this.GetTable<NOT_CLOSE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENGINEER_BUDGET")]
	public partial class ENGINEER_BUDGET
	{
		
		private int _ID;
		
		private string _HOST;
		
		private string _ENGINEER_NAME;
		
		private string _BUDGET;
		
		private string _UPSET_PRICE;
		
		private string _AWARD_PRICE;
		
		private string _DATE;
		
		private string _COMPANY;
		
		public ENGINEER_BUDGET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOST", DbType="NVarChar(MAX)")]
		public string HOST
		{
			get
			{
				return this._HOST;
			}
			set
			{
				if ((this._HOST != value))
				{
					this._HOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENGINEER_NAME", DbType="NVarChar(MAX)")]
		public string ENGINEER_NAME
		{
			get
			{
				return this._ENGINEER_NAME;
			}
			set
			{
				if ((this._ENGINEER_NAME != value))
				{
					this._ENGINEER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUDGET", DbType="NVarChar(MAX)")]
		public string BUDGET
		{
			get
			{
				return this._BUDGET;
			}
			set
			{
				if ((this._BUDGET != value))
				{
					this._BUDGET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPSET_PRICE", DbType="NVarChar(MAX)")]
		public string UPSET_PRICE
		{
			get
			{
				return this._UPSET_PRICE;
			}
			set
			{
				if ((this._UPSET_PRICE != value))
				{
					this._UPSET_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWARD_PRICE", DbType="NVarChar(MAX)")]
		public string AWARD_PRICE
		{
			get
			{
				return this._AWARD_PRICE;
			}
			set
			{
				if ((this._AWARD_PRICE != value))
				{
					this._AWARD_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="NVarChar(MAX)")]
		public string DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="NVarChar(MAX)")]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this._COMPANY = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENGINEER_INFO")]
	public partial class ENGINEER_INFO
	{
		
		private string _AC_NO;
		
		private string _ST_NO;
		
		private string _SNO;
		
		private string _APPMODE;
		
		private string _X;
		
		private string _Y;
		
		private string _APPTIME;
		
		private string _APP_NAME;
		
		private string _C_NAME;
		
		private string _ADDR;
		
		private string _CB_DA;
		
		private string _CE_DA;
		
		private string _CO_TI;
		
		private string _TC_MA;
		
		private string _TC_MA3;
		
		private string _NPURP;
		
		private string _DTYPE;
		
		public ENGINEER_INFO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_NO", DbType="NVarChar(MAX)")]
		public string AC_NO
		{
			get
			{
				return this._AC_NO;
			}
			set
			{
				if ((this._AC_NO != value))
				{
					this._AC_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_NO", DbType="NVarChar(MAX)")]
		public string ST_NO
		{
			get
			{
				return this._ST_NO;
			}
			set
			{
				if ((this._ST_NO != value))
				{
					this._ST_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="NVarChar(MAX)")]
		public string SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPMODE", DbType="NVarChar(MAX)")]
		public string APPMODE
		{
			get
			{
				return this._APPMODE;
			}
			set
			{
				if ((this._APPMODE != value))
				{
					this._APPMODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X", DbType="NVarChar(MAX)")]
		public string X
		{
			get
			{
				return this._X;
			}
			set
			{
				if ((this._X != value))
				{
					this._X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="NVarChar(MAX)")]
		public string Y
		{
			get
			{
				return this._Y;
			}
			set
			{
				if ((this._Y != value))
				{
					this._Y = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPTIME", DbType="NVarChar(MAX)")]
		public string APPTIME
		{
			get
			{
				return this._APPTIME;
			}
			set
			{
				if ((this._APPTIME != value))
				{
					this._APPTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_NAME", DbType="NVarChar(MAX)")]
		public string APP_NAME
		{
			get
			{
				return this._APP_NAME;
			}
			set
			{
				if ((this._APP_NAME != value))
				{
					this._APP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NAME", DbType="NVarChar(MAX)")]
		public string C_NAME
		{
			get
			{
				return this._C_NAME;
			}
			set
			{
				if ((this._C_NAME != value))
				{
					this._C_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR", DbType="NVarChar(MAX)")]
		public string ADDR
		{
			get
			{
				return this._ADDR;
			}
			set
			{
				if ((this._ADDR != value))
				{
					this._ADDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CB_DA", DbType="NVarChar(MAX)")]
		public string CB_DA
		{
			get
			{
				return this._CB_DA;
			}
			set
			{
				if ((this._CB_DA != value))
				{
					this._CB_DA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CE_DA", DbType="NVarChar(MAX)")]
		public string CE_DA
		{
			get
			{
				return this._CE_DA;
			}
			set
			{
				if ((this._CE_DA != value))
				{
					this._CE_DA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_TI", DbType="NVarChar(MAX)")]
		public string CO_TI
		{
			get
			{
				return this._CO_TI;
			}
			set
			{
				if ((this._CO_TI != value))
				{
					this._CO_TI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC_MA", DbType="NVarChar(MAX)")]
		public string TC_MA
		{
			get
			{
				return this._TC_MA;
			}
			set
			{
				if ((this._TC_MA != value))
				{
					this._TC_MA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC_MA3", DbType="NVarChar(MAX)")]
		public string TC_MA3
		{
			get
			{
				return this._TC_MA3;
			}
			set
			{
				if ((this._TC_MA3 != value))
				{
					this._TC_MA3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPURP", DbType="NVarChar(MAX)")]
		public string NPURP
		{
			get
			{
				return this._NPURP;
			}
			set
			{
				if ((this._NPURP != value))
				{
					this._NPURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTYPE", DbType="NVarChar(MAX)")]
		public string DTYPE
		{
			get
			{
				return this._DTYPE;
			}
			set
			{
				if ((this._DTYPE != value))
				{
					this._DTYPE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOT_CLOSE")]
	public partial class NOT_CLOSE
	{
		
		private string _ID;
		
		private string _BUDGET_YEAR;
		
		private string _HOST;
		
		private string _ENGINEER_NAME;
		
		private string _CONTRACT_NUM;
		
		private string _LOCATION;
		
		private string _COMPANY;
		
		private string _AWARD_PRICE;
		
		private string _EX_PRICE;
		
		private string _SCHEDULED_DATE;
		
		private string _RE_SCHEDULED_DATE;
		
		private string _REAL_DATE;
		
		private string _ACCEPT_DATE;
		
		private string _ACCEPT_DATE2;
		
		private string _RE_ACCEPT_DATE;
		
		private string _RE_ACCEPT_DATE2;
		
		private string _FINISH_DATE;
		
		private string _RE_FINISH_DATE;
		
		public NOT_CLOSE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUDGET_YEAR", DbType="NChar(10)")]
		public string BUDGET_YEAR
		{
			get
			{
				return this._BUDGET_YEAR;
			}
			set
			{
				if ((this._BUDGET_YEAR != value))
				{
					this._BUDGET_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOST", DbType="NChar(10)")]
		public string HOST
		{
			get
			{
				return this._HOST;
			}
			set
			{
				if ((this._HOST != value))
				{
					this._HOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENGINEER_NAME", DbType="NChar(10)")]
		public string ENGINEER_NAME
		{
			get
			{
				return this._ENGINEER_NAME;
			}
			set
			{
				if ((this._ENGINEER_NAME != value))
				{
					this._ENGINEER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACT_NUM", DbType="NChar(10)")]
		public string CONTRACT_NUM
		{
			get
			{
				return this._CONTRACT_NUM;
			}
			set
			{
				if ((this._CONTRACT_NUM != value))
				{
					this._CONTRACT_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="NChar(10)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="NChar(10)")]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this._COMPANY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWARD_PRICE", DbType="NChar(10)")]
		public string AWARD_PRICE
		{
			get
			{
				return this._AWARD_PRICE;
			}
			set
			{
				if ((this._AWARD_PRICE != value))
				{
					this._AWARD_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EX_PRICE", DbType="NChar(10)")]
		public string EX_PRICE
		{
			get
			{
				return this._EX_PRICE;
			}
			set
			{
				if ((this._EX_PRICE != value))
				{
					this._EX_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULED_DATE", DbType="NChar(10)")]
		public string SCHEDULED_DATE
		{
			get
			{
				return this._SCHEDULED_DATE;
			}
			set
			{
				if ((this._SCHEDULED_DATE != value))
				{
					this._SCHEDULED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_SCHEDULED_DATE", DbType="NChar(10)")]
		public string RE_SCHEDULED_DATE
		{
			get
			{
				return this._RE_SCHEDULED_DATE;
			}
			set
			{
				if ((this._RE_SCHEDULED_DATE != value))
				{
					this._RE_SCHEDULED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REAL_DATE", DbType="NChar(10)")]
		public string REAL_DATE
		{
			get
			{
				return this._REAL_DATE;
			}
			set
			{
				if ((this._REAL_DATE != value))
				{
					this._REAL_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCEPT_DATE", DbType="NChar(10)")]
		public string ACCEPT_DATE
		{
			get
			{
				return this._ACCEPT_DATE;
			}
			set
			{
				if ((this._ACCEPT_DATE != value))
				{
					this._ACCEPT_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCEPT_DATE2", DbType="NChar(10)")]
		public string ACCEPT_DATE2
		{
			get
			{
				return this._ACCEPT_DATE2;
			}
			set
			{
				if ((this._ACCEPT_DATE2 != value))
				{
					this._ACCEPT_DATE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_ACCEPT_DATE", DbType="NChar(10)")]
		public string RE_ACCEPT_DATE
		{
			get
			{
				return this._RE_ACCEPT_DATE;
			}
			set
			{
				if ((this._RE_ACCEPT_DATE != value))
				{
					this._RE_ACCEPT_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_ACCEPT_DATE2", DbType="NChar(10)")]
		public string RE_ACCEPT_DATE2
		{
			get
			{
				return this._RE_ACCEPT_DATE2;
			}
			set
			{
				if ((this._RE_ACCEPT_DATE2 != value))
				{
					this._RE_ACCEPT_DATE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_DATE", DbType="NChar(10)")]
		public string FINISH_DATE
		{
			get
			{
				return this._FINISH_DATE;
			}
			set
			{
				if ((this._FINISH_DATE != value))
				{
					this._FINISH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_FINISH_DATE", DbType="NChar(10)")]
		public string RE_FINISH_DATE
		{
			get
			{
				return this._RE_FINISH_DATE;
			}
			set
			{
				if ((this._RE_FINISH_DATE != value))
				{
					this._RE_FINISH_DATE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
