#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="budgetDB")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertSUMMARY_COMPARE(SUMMARY_COMPARE instance);
    partial void UpdateSUMMARY_COMPARE(SUMMARY_COMPARE instance);
    partial void DeleteSUMMARY_COMPARE(SUMMARY_COMPARE instance);
    partial void InsertSUMMARY_TYPE(SUMMARY_TYPE instance);
    partial void UpdateSUMMARY_TYPE(SUMMARY_TYPE instance);
    partial void DeleteSUMMARY_TYPE(SUMMARY_TYPE instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.budgetDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ENGINEER_INFO> ENGINEER_INFO
		{
			get
			{
				return this.GetTable<ENGINEER_INFO>();
			}
		}
		
		public System.Data.Linq.Table<NOT_CLOSE> NOT_CLOSE
		{
			get
			{
				return this.GetTable<NOT_CLOSE>();
			}
		}
		
		public System.Data.Linq.Table<ENGINEER_BUDGET> ENGINEER_BUDGET
		{
			get
			{
				return this.GetTable<ENGINEER_BUDGET>();
			}
		}
		
		public System.Data.Linq.Table<SUMMARY_COMPARE> SUMMARY_COMPARE
		{
			get
			{
				return this.GetTable<SUMMARY_COMPARE>();
			}
		}
		
		public System.Data.Linq.Table<SUMMARY_TYPE> SUMMARY_TYPE
		{
			get
			{
				return this.GetTable<SUMMARY_TYPE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENGINEER_INFO")]
	public partial class ENGINEER_INFO
	{
		
		private string _AC_NO;
		
		private string _ST_NO;
		
		private string _SNO;
		
		private string _APPMODE;
		
		private string _X;
		
		private string _Y;
		
		private string _APPTIME;
		
		private string _APP_NAME;
		
		private string _C_NAME;
		
		private string _ADDR;
		
		private string _CB_DA;
		
		private string _CE_DA;
		
		private string _CO_TI;
		
		private string _TC_MA;
		
		private string _TC_MA3;
		
		private string _NPURP;
		
		private string _DTYPE;
		
		public ENGINEER_INFO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_NO", DbType="NVarChar(MAX)")]
		public string AC_NO
		{
			get
			{
				return this._AC_NO;
			}
			set
			{
				if ((this._AC_NO != value))
				{
					this._AC_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_NO", DbType="NVarChar(MAX)")]
		public string ST_NO
		{
			get
			{
				return this._ST_NO;
			}
			set
			{
				if ((this._ST_NO != value))
				{
					this._ST_NO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="NVarChar(MAX)")]
		public string SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPMODE", DbType="NVarChar(MAX)")]
		public string APPMODE
		{
			get
			{
				return this._APPMODE;
			}
			set
			{
				if ((this._APPMODE != value))
				{
					this._APPMODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X", DbType="NVarChar(MAX)")]
		public string X
		{
			get
			{
				return this._X;
			}
			set
			{
				if ((this._X != value))
				{
					this._X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y", DbType="NVarChar(MAX)")]
		public string Y
		{
			get
			{
				return this._Y;
			}
			set
			{
				if ((this._Y != value))
				{
					this._Y = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APPTIME", DbType="NVarChar(MAX)")]
		public string APPTIME
		{
			get
			{
				return this._APPTIME;
			}
			set
			{
				if ((this._APPTIME != value))
				{
					this._APPTIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APP_NAME", DbType="NVarChar(MAX)")]
		public string APP_NAME
		{
			get
			{
				return this._APP_NAME;
			}
			set
			{
				if ((this._APP_NAME != value))
				{
					this._APP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NAME", DbType="NVarChar(MAX)")]
		public string C_NAME
		{
			get
			{
				return this._C_NAME;
			}
			set
			{
				if ((this._C_NAME != value))
				{
					this._C_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDR", DbType="NVarChar(MAX)")]
		public string ADDR
		{
			get
			{
				return this._ADDR;
			}
			set
			{
				if ((this._ADDR != value))
				{
					this._ADDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CB_DA", DbType="NVarChar(MAX)")]
		public string CB_DA
		{
			get
			{
				return this._CB_DA;
			}
			set
			{
				if ((this._CB_DA != value))
				{
					this._CB_DA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CE_DA", DbType="NVarChar(MAX)")]
		public string CE_DA
		{
			get
			{
				return this._CE_DA;
			}
			set
			{
				if ((this._CE_DA != value))
				{
					this._CE_DA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_TI", DbType="NVarChar(MAX)")]
		public string CO_TI
		{
			get
			{
				return this._CO_TI;
			}
			set
			{
				if ((this._CO_TI != value))
				{
					this._CO_TI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC_MA", DbType="NVarChar(MAX)")]
		public string TC_MA
		{
			get
			{
				return this._TC_MA;
			}
			set
			{
				if ((this._TC_MA != value))
				{
					this._TC_MA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC_MA3", DbType="NVarChar(MAX)")]
		public string TC_MA3
		{
			get
			{
				return this._TC_MA3;
			}
			set
			{
				if ((this._TC_MA3 != value))
				{
					this._TC_MA3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPURP", DbType="NVarChar(MAX)")]
		public string NPURP
		{
			get
			{
				return this._NPURP;
			}
			set
			{
				if ((this._NPURP != value))
				{
					this._NPURP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTYPE", DbType="NVarChar(MAX)")]
		public string DTYPE
		{
			get
			{
				return this._DTYPE;
			}
			set
			{
				if ((this._DTYPE != value))
				{
					this._DTYPE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOT_CLOSE")]
	public partial class NOT_CLOSE
	{
		
		private string _ID;
		
		private string _BUDGET_YEAR;
		
		private string _HOST;
		
		private string _ENGINEER_NAME;
		
		private string _CONTRACT_NUM;
		
		private string _LOCATION;
		
		private string _COMPANY;
		
		private string _AWARD_PRICE;
		
		private string _EX_PRICE;
		
		private string _SCHEDULED_DATE;
		
		private string _RE_SCHEDULED_DATE;
		
		private string _REAL_DATE;
		
		private string _ACCEPT_DATE;
		
		private string _ACCEPT_DATE2;
		
		private string _RE_ACCEPT_DATE;
		
		private string _RE_ACCEPT_DATE2;
		
		private string _FINISH_DATE;
		
		private string _RE_FINISH_DATE;
		
		public NOT_CLOSE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NChar(10)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUDGET_YEAR", DbType="NChar(10)")]
		public string BUDGET_YEAR
		{
			get
			{
				return this._BUDGET_YEAR;
			}
			set
			{
				if ((this._BUDGET_YEAR != value))
				{
					this._BUDGET_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOST", DbType="NChar(10)")]
		public string HOST
		{
			get
			{
				return this._HOST;
			}
			set
			{
				if ((this._HOST != value))
				{
					this._HOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENGINEER_NAME", DbType="NChar(10)")]
		public string ENGINEER_NAME
		{
			get
			{
				return this._ENGINEER_NAME;
			}
			set
			{
				if ((this._ENGINEER_NAME != value))
				{
					this._ENGINEER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTRACT_NUM", DbType="NChar(10)")]
		public string CONTRACT_NUM
		{
			get
			{
				return this._CONTRACT_NUM;
			}
			set
			{
				if ((this._CONTRACT_NUM != value))
				{
					this._CONTRACT_NUM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="NChar(10)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this._LOCATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="NChar(10)")]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this._COMPANY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWARD_PRICE", DbType="NChar(10)")]
		public string AWARD_PRICE
		{
			get
			{
				return this._AWARD_PRICE;
			}
			set
			{
				if ((this._AWARD_PRICE != value))
				{
					this._AWARD_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EX_PRICE", DbType="NChar(10)")]
		public string EX_PRICE
		{
			get
			{
				return this._EX_PRICE;
			}
			set
			{
				if ((this._EX_PRICE != value))
				{
					this._EX_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCHEDULED_DATE", DbType="NChar(10)")]
		public string SCHEDULED_DATE
		{
			get
			{
				return this._SCHEDULED_DATE;
			}
			set
			{
				if ((this._SCHEDULED_DATE != value))
				{
					this._SCHEDULED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_SCHEDULED_DATE", DbType="NChar(10)")]
		public string RE_SCHEDULED_DATE
		{
			get
			{
				return this._RE_SCHEDULED_DATE;
			}
			set
			{
				if ((this._RE_SCHEDULED_DATE != value))
				{
					this._RE_SCHEDULED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REAL_DATE", DbType="NChar(10)")]
		public string REAL_DATE
		{
			get
			{
				return this._REAL_DATE;
			}
			set
			{
				if ((this._REAL_DATE != value))
				{
					this._REAL_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCEPT_DATE", DbType="NChar(10)")]
		public string ACCEPT_DATE
		{
			get
			{
				return this._ACCEPT_DATE;
			}
			set
			{
				if ((this._ACCEPT_DATE != value))
				{
					this._ACCEPT_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCEPT_DATE2", DbType="NChar(10)")]
		public string ACCEPT_DATE2
		{
			get
			{
				return this._ACCEPT_DATE2;
			}
			set
			{
				if ((this._ACCEPT_DATE2 != value))
				{
					this._ACCEPT_DATE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_ACCEPT_DATE", DbType="NChar(10)")]
		public string RE_ACCEPT_DATE
		{
			get
			{
				return this._RE_ACCEPT_DATE;
			}
			set
			{
				if ((this._RE_ACCEPT_DATE != value))
				{
					this._RE_ACCEPT_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_ACCEPT_DATE2", DbType="NChar(10)")]
		public string RE_ACCEPT_DATE2
		{
			get
			{
				return this._RE_ACCEPT_DATE2;
			}
			set
			{
				if ((this._RE_ACCEPT_DATE2 != value))
				{
					this._RE_ACCEPT_DATE2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINISH_DATE", DbType="NChar(10)")]
		public string FINISH_DATE
		{
			get
			{
				return this._FINISH_DATE;
			}
			set
			{
				if ((this._FINISH_DATE != value))
				{
					this._FINISH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RE_FINISH_DATE", DbType="NChar(10)")]
		public string RE_FINISH_DATE
		{
			get
			{
				return this._RE_FINISH_DATE;
			}
			set
			{
				if ((this._RE_FINISH_DATE != value))
				{
					this._RE_FINISH_DATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENGINEER_BUDGET")]
	public partial class ENGINEER_BUDGET
	{
		
		private int _ID;
		
		private string _HOST;
		
		private string _ENGINEER_NAME;
		
		private string _BUDGET;
		
		private string _UPSET_PRICE;
		
		private string _AWARD_PRICE;
		
		private string _DATE;
		
		private string _COMPANY;
		
		private System.Nullable<int> _AGREE;
		
		private System.Nullable<int> _DISAGREE;
		
		private System.Nullable<int> _D_RANK;
		
		private System.Nullable<int> _M_RANK;
		
		private System.Nullable<int> _Y_RANK;
		
		public ENGINEER_BUDGET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOST", DbType="NVarChar(MAX)")]
		public string HOST
		{
			get
			{
				return this._HOST;
			}
			set
			{
				if ((this._HOST != value))
				{
					this._HOST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENGINEER_NAME", DbType="NVarChar(MAX)")]
		public string ENGINEER_NAME
		{
			get
			{
				return this._ENGINEER_NAME;
			}
			set
			{
				if ((this._ENGINEER_NAME != value))
				{
					this._ENGINEER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BUDGET", DbType="NVarChar(MAX)")]
		public string BUDGET
		{
			get
			{
				return this._BUDGET;
			}
			set
			{
				if ((this._BUDGET != value))
				{
					this._BUDGET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPSET_PRICE", DbType="NVarChar(MAX)")]
		public string UPSET_PRICE
		{
			get
			{
				return this._UPSET_PRICE;
			}
			set
			{
				if ((this._UPSET_PRICE != value))
				{
					this._UPSET_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWARD_PRICE", DbType="NVarChar(MAX)")]
		public string AWARD_PRICE
		{
			get
			{
				return this._AWARD_PRICE;
			}
			set
			{
				if ((this._AWARD_PRICE != value))
				{
					this._AWARD_PRICE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="NVarChar(MAX)")]
		public string DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this._DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="NVarChar(MAX)")]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this._COMPANY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGREE", DbType="Int")]
		public System.Nullable<int> AGREE
		{
			get
			{
				return this._AGREE;
			}
			set
			{
				if ((this._AGREE != value))
				{
					this._AGREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISAGREE", DbType="Int")]
		public System.Nullable<int> DISAGREE
		{
			get
			{
				return this._DISAGREE;
			}
			set
			{
				if ((this._DISAGREE != value))
				{
					this._DISAGREE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_RANK", DbType="Int")]
		public System.Nullable<int> D_RANK
		{
			get
			{
				return this._D_RANK;
			}
			set
			{
				if ((this._D_RANK != value))
				{
					this._D_RANK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M_RANK", DbType="Int")]
		public System.Nullable<int> M_RANK
		{
			get
			{
				return this._M_RANK;
			}
			set
			{
				if ((this._M_RANK != value))
				{
					this._M_RANK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_RANK", DbType="Int")]
		public System.Nullable<int> Y_RANK
		{
			get
			{
				return this._Y_RANK;
			}
			set
			{
				if ((this._Y_RANK != value))
				{
					this._Y_RANK = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUMMARY_COMPARE")]
	public partial class SUMMARY_COMPARE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _HIGH_BUDGET;
		
		private int _LOW_BUDGET;
		
		private string _HIGH_NAME;
		
		private string _LOW_NAME;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnHIGH_BUDGETChanging(int value);
    partial void OnHIGH_BUDGETChanged();
    partial void OnLOW_BUDGETChanging(int value);
    partial void OnLOW_BUDGETChanged();
    partial void OnHIGH_NAMEChanging(string value);
    partial void OnHIGH_NAMEChanged();
    partial void OnLOW_NAMEChanging(string value);
    partial void OnLOW_NAMEChanged();
    #endregion
		
		public SUMMARY_COMPARE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIGH_BUDGET", DbType="Int NOT NULL")]
		public int HIGH_BUDGET
		{
			get
			{
				return this._HIGH_BUDGET;
			}
			set
			{
				if ((this._HIGH_BUDGET != value))
				{
					this.OnHIGH_BUDGETChanging(value);
					this.SendPropertyChanging();
					this._HIGH_BUDGET = value;
					this.SendPropertyChanged("HIGH_BUDGET");
					this.OnHIGH_BUDGETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOW_BUDGET", DbType="Int NOT NULL")]
		public int LOW_BUDGET
		{
			get
			{
				return this._LOW_BUDGET;
			}
			set
			{
				if ((this._LOW_BUDGET != value))
				{
					this.OnLOW_BUDGETChanging(value);
					this.SendPropertyChanging();
					this._LOW_BUDGET = value;
					this.SendPropertyChanged("LOW_BUDGET");
					this.OnLOW_BUDGETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIGH_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HIGH_NAME
		{
			get
			{
				return this._HIGH_NAME;
			}
			set
			{
				if ((this._HIGH_NAME != value))
				{
					this.OnHIGH_NAMEChanging(value);
					this.SendPropertyChanging();
					this._HIGH_NAME = value;
					this.SendPropertyChanged("HIGH_NAME");
					this.OnHIGH_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOW_NAME", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string LOW_NAME
		{
			get
			{
				return this._LOW_NAME;
			}
			set
			{
				if ((this._LOW_NAME != value))
				{
					this.OnLOW_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LOW_NAME = value;
					this.SendPropertyChanged("LOW_NAME");
					this.OnLOW_NAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUMMARY_TYPE")]
	public partial class SUMMARY_TYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TYPE;
		
		private int _AWARD_PRICE;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTYPEChanging(string value);
    partial void OnTYPEChanged();
    partial void OnAWARD_PRICEChanging(int value);
    partial void OnAWARD_PRICEChanged();
    #endregion
		
		public SUMMARY_TYPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TYPE
		{
			get
			{
				return this._TYPE;
			}
			set
			{
				if ((this._TYPE != value))
				{
					this.OnTYPEChanging(value);
					this.SendPropertyChanging();
					this._TYPE = value;
					this.SendPropertyChanged("TYPE");
					this.OnTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWARD_PRICE", DbType="Int NOT NULL")]
		public int AWARD_PRICE
		{
			get
			{
				return this._AWARD_PRICE;
			}
			set
			{
				if ((this._AWARD_PRICE != value))
				{
					this.OnAWARD_PRICEChanging(value);
					this.SendPropertyChanging();
					this._AWARD_PRICE = value;
					this.SendPropertyChanged("AWARD_PRICE");
					this.OnAWARD_PRICEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
